import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { runtimeOwnedAllows, runtimeOwnedFile } from '../src/domain/workspace/runtime_owned_file.js';

/**
 * A refusal has to name the action that replaces it.
 *
 * These paths are created by Runtime, so a Step refused one of them cannot discover why by guessing:
 * `not in this Step's writable allowlist` describes the allowlist, not the ownership. Three live
 * Tickets lost their entire attempt budget to that — one on the fixture directory, one on
 * `tests/conftest.py`, and an S003 on a fabricated assessment field. The registry exists so the owner
 * and the remedy arrive with the denial.
 */
describe('runtime-owned files', () => {
  it('names both the owner and the replacement action for the dependency manifest', () => {
    const owned = runtimeOwnedFile('requirements.txt', 'python');
    expect(owned).toBeDefined();
    expect(owned!.remedy).toMatch(/add_dependency/u);
    // No write of any kind: the file is rendered from plan.dependencies.
    expect(runtimeOwnedAllows(owned!, 'write')).toBe(false);
    expect(runtimeOwnedAllows(owned!, 'append')).toBe(false);
  });

  // package.json is authored by HIGH_LEVEL_DESIGN, so claiming it would refuse a Step its own work.
  it('does not claim the TypeScript manifest, which a Step does own', () => {
    expect(runtimeOwnedFile('package.json', 'typescript')).toBeUndefined();
    expect(runtimeOwnedFile('requirements.txt', 'typescript')).toBeUndefined();
  });

  /**
   * The reason for refusing a rewrite is the content Runtime already put there. With no file on
   * disk there is no such content, and refusing blocks the only repair available while asserting
   * something false — that Runtime "puts the bootstrap at the top". A live run spent eight attempts
   * there: the Step read the refusal, checked the directory, found nothing, and tried again.
   */
  it('lets a Step create conftest.py when Runtime has not written one', () => {
    const owned = runtimeOwnedFile('tests/conftest.py', 'python')!;
    expect(runtimeOwnedAllows(owned, 'write', false)).toBe(true);
  });

  it('lets a Step append shared fixtures to conftest.py but never rewrite it', () => {
    const owned = runtimeOwnedFile('tests/conftest.py', 'python');
    expect(owned).toBeDefined();
    expect(runtimeOwnedAllows(owned!, 'append')).toBe(true);
    expect(runtimeOwnedAllows(owned!, 'write')).toBe(false);
    // The remedy must say what appending is for, and what rewriting would destroy.
    expect(owned!.remedy).toMatch(/append_file/u);
    expect(owned!.remedy).toMatch(/sys\.path/u);
  });
});

/**
 * The registry decides for owned paths and the allowlist decides for the rest.
 *
 * Requiring both would leave `tests/conftest.py` unreachable — no plan declares it — which is the
 * gap that made a Step rewrite the same file into the same denial six times.
 */
describe('write guards consult the registry', () => {
  let root = '';
  const ctxFor = async (allowedWrites: string[]) => {
    const { Workspace } = await import('../src/workspace/workspace.js');
    return {
      ws: new Workspace(root),
      allowedWrites,
      stepId: 'S004',
      language: 'python' as const,
      sandbox: {} as never,
    } as never;
  };

  beforeEach(async () => {
    root = await fs.mkdtemp(path.join(os.tmpdir(), 'xcompiler-owned-'));
    await fs.mkdir(path.join(root, 'tests'), { recursive: true });
    await fs.writeFile(path.join(root, 'tests/conftest.py'), '# Auto-generated by XCompiler\nimport sys\n');
  });
  afterEach(async () => {
    await fs.rm(root, { recursive: true, force: true });
  });

  it('allows write_file to create conftest.py when it is absent', async () => {
    const { promises } = await import('node:fs');
    await promises.rm(path.join(root, 'tests/conftest.py'));
    const { writeFileTool } = await import('../src/tools/fs.js');
    const result = await writeFileTool.run(
      { path: 'tests/conftest.py', content: 'import sys\n' },
      await ctxFor(['src/main.py']),
    );
    expect(result.ok).toBe(true);
  });

  it('refuses write_file on conftest.py with the remedy, not with the allowlist', async () => {
    const { writeFileTool } = await import('../src/tools/fs.js');
    const result = await writeFileTool.run(
      { path: 'tests/conftest.py', content: 'clobbered' },
      await ctxFor(['src/main.py']),
    );
    expect(result.ok).toBe(false);
    expect(result.error).toMatch(/append_file/u);
    // The generic message is what left the Step nothing to try.
    expect(result.error).not.toMatch(/writable allowlist/u);
  });

  it('allows append_file on conftest.py even though no plan declares it', async () => {
    const { appendFileTool } = await import('../src/tools/fs.js');
    const result = await appendFileTool.run(
      { path: 'tests/conftest.py', content: '\nimport pytest\n\n@pytest.fixture\ndef sample_dbc():\n    return "x"\n' },
      await ctxFor(['src/main.py']),
    );
    expect(result.ok).toBe(true);
    // The bootstrap it was appended below must survive.
    const after = await fs.readFile(path.join(root, 'tests/conftest.py'), 'utf8');
    expect(after).toContain('import sys');
    expect(after).toContain('sample_dbc');
  });

  it('refuses replace_in_file on conftest.py, which rewrites in place', async () => {
    const { replaceInFileTool } = await import('../src/tools/edit.js');
    const result = await replaceInFileTool.run(
      { path: 'tests/conftest.py', find: 'import sys', replace: 'pass' },
      await ctxFor(['src/main.py']),
    );
    expect(result.ok).toBe(false);
    expect(result.error).toMatch(/Runtime-owned|append_file/u);
  });
});
