#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { scriptMessage as m } from './script_i18n.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const packagePath = path.join(root, 'package.json');
const lockPath = path.join(root, 'package-lock.json');
const generatedPath = path.join(root, 'src/version.ts');
const semverPattern = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/;

const readJson = async (file) => JSON.parse(await readFile(file, 'utf8'));
const writeJson = async (file, value) => writeFile(file, `${JSON.stringify(value, null, 2)}\n`);

function assertMetadata(pkg) {
  if (!semverPattern.test(pkg.version)) {
    throw new Error(m('version.invalid_package', pkg.version));
  }
  const apiVersion = pkg.toaa?.pluginApiVersion;
  if (!Number.isInteger(apiVersion) || apiVersion < 1) {
    throw new Error(m('version.invalid_plugin_api', String(apiVersion)));
  }
}

function generatedSource(pkg) {
  return `// Generated by scripts/version.mjs from package.json. Do not edit manually.\n` +
    `export const TOAA_VERSION = ${JSON.stringify(pkg.version)};\n` +
    `export const TOAA_PLUGIN_API_VERSION = ${pkg.toaa.pluginApiVersion};\n`;
}

async function sync(pkg, lock) {
  lock.version = pkg.version;
  if (!lock.packages?.['']) throw new Error(m('version.lock_root_missing'));
  lock.packages[''].version = pkg.version;
  await Promise.all([
    writeJson(packagePath, pkg),
    writeJson(lockPath, lock),
    writeFile(generatedPath, generatedSource(pkg)),
  ]);
}

const command = process.argv[2] ?? 'check';
const pkg = await readJson(packagePath);
const lock = await readJson(lockPath);

if (command === 'set') {
  const version = process.argv[3];
  if (!version) throw new Error(m('version.set_usage'));
  pkg.version = version;
}
assertMetadata(pkg);

if (command === 'sync' || command === 'set') {
  await sync(pkg, lock);
  console.log(m('version.synced', pkg.version, pkg.toaa.pluginApiVersion));
} else if (command === 'check') {
  const generated = await readFile(generatedPath, 'utf8').catch(() => '');
  const errors = [];
  if (lock.version !== pkg.version) errors.push(m('version.lock_mismatch', lock.version));
  if (lock.packages?.['']?.version !== pkg.version) {
    errors.push(m('version.lock_root_mismatch', lock.packages?.['']?.version));
  }
  if (generated !== generatedSource(pkg)) errors.push(m('version.runtime_stale'));
  if (errors.length > 0) {
    throw new Error(m('version.metadata_mismatch', pkg.version, errors.join('; ')));
  }
  console.log(m('version.consistent', pkg.version, pkg.toaa.pluginApiVersion));
} else {
  throw new Error(m('version.unknown_command', command));
}
